- name: Creating the Openshift installation configuration file
  ansible.builtin.template:
    src: "install-config.yaml.j2"
    dest: "installer/install-config.yaml"
    mode: '0644'
  when: not kubeconfig_stat_result.stat.exists
