- block:
  - name: Backup Kubernetes manifests
    ansible.builtin.copy:
      src: "installer/manifests/"
      dest: "installer/manifests.bak/"
      mode: '0755'

  - name: Creating the Ignition config files
    ansible.builtin.shell:
      cmd: "openshift-install create ignition-configs --dir installer/"
  when: not kubeconfig_stat_result.stat.exists